### ISSUE TITLE
[question] result of the experiments shows too high variation

### ISSUE THREAD

**Issue by pixar0407** [seolhokim/Mujoco-Pytorch#2]
Hello, @seolhokim  again.

I hope you have good week.
I have another question, if you don't mind.
My question consists of 3 questions, **MAIN QUESTION 1**, **SUB QUESTION 1 and 2**.

I ran multiple 'main.py' of your code. That is simulation for hopper around 1000 times run.
My question is that actor_loss, critic_loss, score all vary. (suffered from variation)
I learn that result of reinforcement learning is variant. But i didn't expect this variant. 
(**MAIN QUESTION 1**)Is it normal? Or did i miss something and get it wrong?
(제가 main.py 를 여러번 돌려 보았습니다. hopper를 1000번씩 돌려보는 seolhokim님의 기본 setting대로 입니다.
제 질문은 actor_loss, critic_loss, score의 분포가 너무 다양하다는 것입니다.
저는 현재 DRL 뉴비인데, 공부한 바로는 DRL 결과의 분포는 일반적인 supervised learning에 비해 분포가 심할 수 있다고 배웠습니다.
그러나 이렇게 심할 줄은 몰랐습니다. 이게 정상인가요? 아니면 제가 뭔가를 놓쳐서 잘못된 결과를 받은 건가요?)

(참고)
I didn't fix random_seed
(**SUB QUESTION 1**) Do i have to fix random_seed?
(**SUB QUESTION 2** )Do i have to run 1000000 times like ppo original paper? 

![multiple_try_ppo_hopper](https://user-images.githubusercontent.com/26530798/157145751-2709746b-ffbf-4cbf-ba8d-eec79467a3fa.JPG)
This picture shows results of multiple runs of 'main.py'. I set the 'smoothing' as 0.999. You see that all the last score of multiple runs end up in different value. High value of score is 2091 and lowest value of score is 985. And last score of critic loss also vary. The highest value of critic loss is 2.175 and the lowest value of critic loss is 0.3734. 
(위 사진은 main.py를 여러번 돌린 결과를 tensorboard로 표현한 것입니다. 명확한 표현을 위해서 'smoothing'은 0.999로 세팅했습니다. 보시면 각 score value가 1000번째(마지막) run에 다양한 값으로 나타나 있습니다. 가장 큰 값은 2091인데, 가장 작은 값은 985입니다. critic loss 또한 사정은 같으며, 가장 큰 값은 2.175이고, 가장 작은 값은 0.3734입니다. )

**Comment by seolhokim** [comment]
Hi, If you look at some papers, the authors try experiments several times and show mean and std. It is a natural phenomenon. (Not always) Don't pay too much attention to the loss value now. Soon, you will have the opportunity to understand loss and do debugging and research.

Many papers mention performance in relation to the amount of frames actually interacting with. This PPO implementation trains 2048 frames in 1 epoch(You can find it in config.ini file)

**Comment by pixar0407** [comment]
@seolhokim 

Thanks for the comment.
Okay. I will run several times and derive mean and std from them.
And I will read more papers for better understanding.

And Yes. I do notice the 2048 frames (in config.ini file). I believe that 'frame' means 'trajectory length'. Right?

**Comment by seolhokim** [comment]
Right. one frame is equal to one interaction with environment.

**Comment by pixar0407** [comment]
Thank you, @seolhokim .

**Comment by pixar0407** [comment]
Good evening, @seolhokim .

After reading some paper as you instructed, I have related and detailed question about this issue.
Please see the Fig3 and Fig4 on these picture.

![a2c](https://user-images.githubusercontent.com/26530798/157231867-569a8971-2408-47f9-9467-17b7bcdc462a.jpg)
![trpo](https://user-images.githubusercontent.com/26530798/157231888-90d71f29-4313-4b86-a3c8-b97e7adcaa20.jpg)

On each description on the pictures, A2C author said that y-axis is averaged over three best cases. And TRPO author said that y-axis is averaged over five runs. 

So, is this what we mean, right?
But my question is that how can this be fair? only five? only three even the best ones?

Even with the five runs, If i choose different five combination, then I will have different figure.
So What i mean is that five or three is too small population. 
Is this RL's custom?

말씀해주신데로, 몇가지 논문을 찾아본 후, 관련 질문이 있어 글 남깁니다.

사진에 나와 있는 figure 설명란에 보면, A2C 저자들은 y-axis가 3가지 best case를 average 했다고 하며, TRPO 저자는 5개 시도를 평균냈다고 합니다.

말씀해 주신 mean과 average가 이걸 뜻하는 것인가요?
하지만 제 의문은 이게 충분히 fair 할 수 있나요? 고작 5개 또는 3개, 그것도 best one만 cherrypicking해서요?

그리고 5개 시도를 평균 낸다고 해도, 만약 제가 다른 5개를 택한다면 그래프가 다르게 나올 것 같습니다.
제 말씀은 5개나 3개는 너무 작은 모집단이 아닌가 해서요.
이게 Reinforcement learning 논문들의 custom인가요?

(말투가 따지는 듯 하다면 죄송합니다 ㅠ 자세히 여쭙느라고 이렇게 문장을 표현하였습니다.)

**Comment by seolhokim** [comment]
I recommend to read this paper. Deep Reinforcement Learning at the Edge of the Statistical Precipice

You will recognize how many computation(time) is needed to test some algorithms in DMC or atari.

**Comment by pixar0407** [comment]
Thank you @seolhokim  for the recommendation.
Have a good night.
