### ISSUE TITLE
Question about average reward

### ISSUE THREAD

**Issue by pixar0407** [seolhokim/Mujoco-Pytorch#3]
Hi again.

Thank you for the quality code. I am using it for long time to build my own project. 

Here is the question. 
How do you normally calculate the average reward?

in your code, there is "print_interval". This averages rewards of last 20 (default)  steps. 
But, when i go to other codes (like openai, spinningup), I think they are using 100 for default length.

So, i know choosing the length is my own choice. 
But, when you think writing a official paper(conference paper), How do you set up for this length?

for example, in the ppo paper (https://arxiv.org/pdf/1707.06347.pdf), in the figure 3, there is reward figure. 
I want to know the default length. 
in the ppo paper, in the a2c paper, they do not reveal how they calculate the average. 

they might average during the total episode?
they might average during the last 100 step?

Help me, if you know.

**Comment by seolhokim** [comment]
Hi. That's a good question. But did you check the [paper](https://arxiv.org/abs/2108.13264) before I recommended? It is important to notify authors' experiments to people. So It needs to check multiple experiments on different seeds for the same task. That's the common mean in papers. But if you want to check agent performance in one task, it is natural to check k-lengths mean in only one experiment. That's the difference.
